blank_issues_enabled: true
contact_links:
  - name: Conda-forge Element chatroom
    url: https://app.element.io/#/room/#conda-forge:matrix.org
    about: Chat to us about conda-forge and ask general questions.
  - name: Conda-forge documentation
    url: https://conda-forge.org/docs/
    about: The complete conda-forge documentation.
  - name: Conda-forge packages
    url: https://conda-forge.org/feedstock-outputs/
    about: For when you have an issue with a specific package.
